pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'mvn clean install package'
                }
            }

        stage('test') {
            steps {
                sh 'mvn clean test'

            }
        }
        stage('deploy to  CloudHub') {
        steps {
         withCredentials([usernamePassword(credentialsId: 'anypoint.credentials', passwordVariable: 'anypoint_psw', usernameVariable: 'anypoint_usr')])
   {

       script {
                
                sh 'mvn clean deploy'
                
                }
             }
}
         
}
   stage('Slack Notify') {
            steps {
               slackSend baseUrl: 'https://ms3inc.slack.com/services/hooks/jenkins-ci/', channel: '#iot-sandbox', color: '#439FE0", message : "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"', message: 'MS3-Sample-api executed successfully ', tokenCredentialId: 'Slack'

            }

}
}
}
